name: Check Build
on: [pull_request]

jobs:
  build:
    name: Check Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Build production bundle
        uses: borales/actions-yarn@v4
        with:
          cmd: build
